name: Build firmware

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
        matrix:
          gcc: ['12.2.Rel1', '13.2.Rel1']
    name: "Build firmware"
    runs-on: ubuntu-latest
    steps:
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: ${{ matrix.gcc }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build
        run: make all

